// ── data.js ───────────────────────────────────────────────────────────────────
// All static game data: images, item metadata, recipes, smash fills.
// Loaded before app.js via <script> tag — defines globals used throughout.
// This is the file the beetlemaster tool modifies when adding new items.
// ─────────────────────────────────────────────────────────────────────────────

// ── IMAGE PATHS ───────────────────────────────────────────────────────────────
const W = 'https://wiki.remilia.org/images'; // wiki base for bg scenes & radbro

const IMAGES = {
  // Beetles — icons
  green:                    'icons/beetles/green.png',
  purple:                   'icons/beetles/purple.png',
  ladybug:                  'icons/beetles/ladybug.png',
  monarch:                  'icons/beetles/monarch.png',
  pond:                     'icons/beetles/pond.png',
  giraffe_weevil:           'icons/beetles/giraffe_weevil.png',
  bumblebee:                'icons/beetles/bumblebee.png',
  golden_tiger:             'icons/beetles/golden_tiger.png',
  widow:                    'icons/beetles/widow.png',
  golden:                   'icons/beetles/golden.png',
  cucumber:                 'icons/beetles/cucumber.png',
  christmas:                'icons/beetles/christmas.png',
  goliath:                  'icons/beetles/goliath.png',
  bombardier:               'icons/beetles/bombardier.png',
  stag:                     'icons/beetles/stag.png',
  skull:                    'icons/beetles/skull.png',
  candycane_tiger_moth:     'icons/beetles/candycane_tiger_moth.png',
  sabertooth_longhorn:      'icons/beetles/sabertooth_longhorn.png',
  pillbug:                  'icons/beetles/pillbug.png',
  imperial_tortoise:        'icons/beetles/imperial_tortoise.png',
  sunset_moth:              'icons/beetles/sunset_moth.png',
  mars_rhino:               'icons/beetles/mars_rhino.png',
  pondhawk:                 'icons/beetles/pondhawk.png',
  blue_longicorn:           'icons/beetles/blue_longicorn.png',
  // Flowers — icons
  daisy:                    'icons/flowers/daisy.png',
  sunflower:                'icons/flowers/sunflower.png',
  poppy:                    'icons/flowers/poppy.png',
  gallic_rose:              'icons/flowers/gallic_rose.png',
  st_johns_wort:            'icons/flowers/st_johns_wort.png',
  milk_thistle:             'icons/flowers/milk_thistle.png',
  larkspur:                 'icons/flowers/larkspur.png',
  petunia:                  'icons/flowers/petunia.png',
  snapdragon:               'icons/flowers/snapdragon.png',
  carnation:                'icons/flowers/carnation.png',
  hellebore:                'icons/flowers/hellebore.png',
  royal_poinciana:          'icons/flowers/royal_poinciana.png',
  marigold:                 'icons/flowers/marigold.png',
  magnolia:                 'icons/flowers/magnolia.png',
  camellia:                 'icons/flowers/camellia.png',
  morning_glory:            'icons/flowers/morning_glory.png',
  pincushion:               'icons/flowers/pincushion.png',
  gazania:                  'icons/flowers/gazania.png',
  black_lotus:              'icons/flowers/black_lotus.png',
  fringed_iris:             'icons/flowers/fringed_iris.png',
  // Pollen — icons
  pollen_common:            'icons/flowers/pollen_common.png',
  pollen_uncommon:          'icons/flowers/pollen_uncommon.png',
  pollen_rare:              'icons/flowers/pollen_rare.png',
  pollen_epic:              'icons/flowers/pollen_epic.png',
  // Hammers — icons
  hammer_t1:                'icons/hammers/hammer_t1.png',
  hammer_t2:                'icons/hammers/hammer_t2.png',
  hammer_t3:                'icons/hammers/hammer_t3.png',
  hammer_t4:                'icons/hammers/hammer_t4.png',
  hammer_t5:                'icons/hammers/hammer_t5.png',
  // Junk cubes + virtual aggregate
  _junk_:                   'icons/junk/junk_cube_t1.png',
  junk_cube_t1:             'icons/junk/junk_cube_t1.png',
  junk_cube_t2:             'icons/junk/junk_cube_t2.png',
  // Junk items
  ballpoint_pen:            'icons/junk/ballpoint_pen.png',
  bendy_straw:              'icons/junk/bendy_straw.png',
  bike_reflector:           'icons/junk/bike_reflector.png',
  bottle_cap:               'icons/junk/bottle_cap.png',
  broken_firework:          'icons/junk/broken_firework.png',
  headphones_90s:           'icons/junk/headphones_90s.png',
  burger_wrapper:           'icons/junk/burger_wrapper.png',
  chewed_eraser:            'icons/junk/chewed_eraser.png',
  event_band:               'icons/junk/event_band.png',
  guitar_pick:              'icons/junk/guitar_pick.png',
  origami_crane:            'icons/junk/origami_crane.png',
  pill_bottle:              'icons/junk/pill_bottle.png',
  button:                   'icons/junk/button.png',
  chip_bag:                 'icons/junk/chip_bag.png',
  chocolate_bar:            'icons/junk/chocolate_bar.png',
  chocolate_wrapper:        'icons/junk/chocolate_wrapper.png',
  cigarette_butt:           'icons/junk/cigarette_butt.png',
  coffee_can:               'icons/junk/coffee_can.png',
  cracker_wrapper:          'icons/junk/cracker_wrapper.png',
  deodorant_can:            'icons/junk/deodorant_can.png',
  empty_noodle_cup:         'icons/junk/empty_noodle_cup.png',
  glue_stick:               'icons/junk/glue_stick.png',
  green_army_man:           'icons/junk/green_army_man.png',
  grenade_pin:              'icons/junk/grenade_pin.png',
  gum_wrapper:              'icons/junk/gum_wrapper.png',
  jack_adapter:             'icons/junk/jack_adapter.png',
  juicebox:                 'icons/junk/juicebox.png',
  marble:                   'icons/junk/marble.png',
  matchbook:                'icons/junk/matchbook.png',
  paperclip:                'icons/junk/paperclip.png',
  pebble:                   'icons/junk/pebble.png',
  pokkiri_box:              'icons/junk/pokkiri_box.png',
  ramune_bottle:            'icons/junk/ramune_bottle.png',
  red_whistle:              'icons/junk/red_whistle.png',
  rubber_band:              'icons/junk/rubber_band.png',
  salt_pepper_packet:       'icons/junk/salt_pepper_packet.png',
  scratch_off:              'icons/junk/scratch_off.png',
  sim_card:                 'icons/junk/sim_card.png',
  smiley_pebble:            'icons/junk/smiley_pebble.png',
  soda_can_tab:             'icons/junk/soda_can_tab.png',
  stamp:                    'icons/junk/stamp.png',
  train_ticket_stub:        'icons/junk/train_ticket_stub.png',
  watch_battery:            'icons/junk/watch_battery.png',
  wine_cork:                'icons/junk/wine_cork.png',
  wristband:                'icons/junk/wristband.png',
  // Artifacts
  gunpowder:                'icons/artifacts/gunpowder.png',
  cattail:                  'icons/artifacts/cattail.png',
  nectar:                   'icons/artifacts/nectar.png',
  moss:                     'icons/artifacts/moss.png',
  pinecone:                 'icons/artifacts/pinecone.png',
  // Special / unique
  specimen_pin:             'icons/artifacts/specimen_pin.png',
  beetleboy_key:            'icons/unique/beetleboy_key.png',
  cheese:                   'icons/cheese/cheese.png',
  // Trophies — icons
  trophy_arrowhead:         'icons/trophies/trophy_arrowhead.webp',
  trophy_chinese_coin:      'icons/trophies/trophy_chinese_coin.webp',
  trophy_compass:           'icons/trophies/trophy_compass.webp',
  trophy_cult_medallion:    'icons/trophies/trophy_cult_medallion.webp',
  trophy_d20:               'icons/trophies/trophy_d20.webp',
  trophy_deck_of_cards:     'icons/trophies/trophy_deck_of_cards.webp',
  trophy_engraved_lighter:  'icons/trophies/trophy_engraved_lighter.webp',
  trophy_goya_miniature:    'icons/trophies/trophy_goya_miniature.webp',
  trophy_jade_cabbage:      'icons/trophies/trophy_jade_cabbage.webp',
  trophy_juex_card:         'icons/trophies/trophy_juex_card.webp',
  trophy_milady_fumoku:     'icons/trophies/trophy_milady_fumoku.webp',
  trophy_mokia:             'icons/trophies/trophy_mokia.webp',
  trophy_oriental_fan:      'icons/trophies/trophy_oriental_fan.webp',
  trophy_police_badge:      'icons/trophies/trophy_police_badge.webp',
  trophy_prism:             'icons/trophies/trophy_prism.webp',
  trophy_remilianet_id:     'icons/trophies/trophy_remilianet_id.webp',
  trophy_roman_dodeca:      'icons/trophies/trophy_roman_dodeca.webp',
  trophy_stradivarius:      'icons/trophies/trophy_stradivarius.webp',
  trophy_thumb_drive:       'icons/trophies/trophy_thumb_drive.webp',
  trophy_titanium_cube:     'icons/trophies/trophy_titanium_cube.webp',
  // Trophies — card art (same image as icon)
  _card_trophy_arrowhead:        'icons/trophies/trophy_arrowhead.webp',
  _card_trophy_chinese_coin:     'icons/trophies/trophy_chinese_coin.webp',
  _card_trophy_compass:          'icons/trophies/trophy_compass.webp',
  _card_trophy_cult_medallion:   'icons/trophies/trophy_cult_medallion.webp',
  _card_trophy_d20:              'icons/trophies/trophy_d20.webp',
  _card_trophy_deck_of_cards:    'icons/trophies/trophy_deck_of_cards.webp',
  _card_trophy_engraved_lighter: 'icons/trophies/trophy_engraved_lighter.webp',
  _card_trophy_goya_miniature:   'icons/trophies/trophy_goya_miniature.webp',
  _card_trophy_jade_cabbage:     'icons/trophies/trophy_jade_cabbage.webp',
  _card_trophy_juex_card:        'icons/trophies/trophy_juex_card.webp',
  _card_trophy_milady_fumoku:    'icons/trophies/trophy_milady_fumoku.webp',
  _card_trophy_mokia:            'icons/trophies/trophy_mokia.webp',
  _card_trophy_oriental_fan:     'icons/trophies/trophy_oriental_fan.webp',
  _card_trophy_police_badge:     'icons/trophies/trophy_police_badge.webp',
  _card_trophy_prism:            'icons/trophies/trophy_prism.webp',
  _card_trophy_remilianet_id:    'icons/trophies/trophy_remilianet_id.webp',
  _card_trophy_roman_dodeca:     'icons/trophies/trophy_roman_dodeca.webp',
  _card_trophy_stradivarius:     'icons/trophies/trophy_stradivarius.webp',
  _card_trophy_thumb_drive:      'icons/trophies/trophy_thumb_drive.webp',
  _card_trophy_titanium_cube:    'icons/trophies/trophy_titanium_cube.webp',
  // Card art — beetles
  _card_green:              'icons/_card/green.webp',
  _card_purple:             'icons/_card/purple.webp',
  _card_ladybug:            'icons/_card/ladybug.webp',
  _card_monarch:            'icons/_card/monarch.webp',
  _card_pond:               'icons/_card/pond.webp',
  _card_cucumber:           'icons/_card/cucumber.webp',
  _card_giraffe_weevil:     'icons/_card/giraffe_weevil.webp',
  _card_bumblebee:          'icons/_card/bumblebee.webp',
  _card_golden_tiger:       'icons/_card/golden_tiger.webp',
  _card_widow:              'icons/_card/widow.webp',
  _card_golden:             'icons/_card/golden.webp',
  _card_christmas:          'icons/_card/christmas.webp',
  _card_goliath:            'icons/_card/goliath.webp',
  _card_bombardier:         'icons/_card/bombardier.webp',
  _card_stag:               'icons/_card/stag.webp',
  _card_skull:              'icons/_card/skull.webp',
  _card_candycane_tiger_moth: 'icons/_card/candycane_tiger_moth.webp',
  _card_sabertooth_longhorn: 'icons/_card/sabertooth_longhorn.webp',
  _card_pillbug:            'icons/_card/pillbug.webp',
  _card_imperial_tortoise:  'icons/_card/imperial_tortoise.webp',
  _card_sunset_moth:        'icons/_card/sunset_moth.webp',
  _card_mars_rhino:         'icons/_card/mars_rhino.webp',
  _card_pondhawk:           'icons/_card/pondhawk.webp',
  _card_blue_longicorn:     'icons/_card/blue_longicorn.webp',
  _card_radbro:             `${W}/3/3c/Radbro.png`,
  // Card art — flowers
  _card_daisy:              'icons/_card/daisy.webp',
  _card_sunflower:          'icons/_card/sunflower.webp',
  _card_poppy:              'icons/_card/poppy.webp',
  _card_gallic_rose:        'icons/_card/gallic_rose.webp',
  _card_milk_thistle:       'icons/_card/milk_thistle.webp',
  _card_marigold:           'icons/_card/marigold.webp',
  _card_magnolia:           'icons/_card/magnolia.webp',
  _card_camellia:           'icons/_card/camellia.webp',
  _card_royal_poinciana:    'icons/_card/royal_poinciana.webp',
  _card_morning_glory:      'icons/_card/morning_glory.webp',
  _card_pincushion:         'icons/_card/pincushion.webp',
  _card_gazania:            'icons/_card/gazania.webp',
  _card_hammer_t3:          'icons/_card/hammer_t3.webp',
  _card_carnation:          'icons/_card/carnation.webp',
  _card_hellebore:          'icons/_card/hellebore.webp',
  _card_black_lotus:        'icons/_card/black_lotus.webp',
  _card_fringed_iris:       'icons/_card/fringed_iris.webp',
  // Card art — junk
  _card_junk_cube_t1:       'icons/_card_junk/junk_cube_t1.webp',
  _card_junk_cube_t2:       'icons/_card_junk/junk_cube_t2.webp',
  _card_bike_reflector:     'icons/_card_junk/bike_reflector.webp',
  _card_bottle_cap:         'icons/_card_junk/bottle_cap.webp',
  _card_chip_bag:           'icons/_card_junk/chip_bag.webp',
  _card_chocolate_bar:      'icons/_card_junk/chocolate_bar.webp',
  _card_chocolate_wrapper:  'icons/_card_junk/chocolate_wrapper.webp',
  _card_cigarette_butt:     'icons/_card_junk/cigarette_butt.webp',
  _card_coffee_can:         'icons/_card_junk/coffee_can.webp',
  _card_cracker_wrapper:    'icons/_card_junk/cracker_wrapper.webp',
  _card_empty_noodle_cup:   'icons/_card_junk/empty_noodle_cup.webp',
  _card_green_army_man:     'icons/_card_junk/green_army_man.webp',
  _card_gum_wrapper:        'icons/_card_junk/gum_wrapper.webp',
  _card_jack_adapter:       'icons/_card_junk/jack_adapter.webp',
  _card_juicebox:           'icons/_card_junk/juicebox.webp',
  _card_marble:             'icons/_card_junk/marble.webp',
  _card_paperclip:          'icons/_card_junk/paperclip.webp',
  _card_pebble:             'icons/_card_junk/pebble.webp',
  _card_pokkiri_box:        'icons/_card_junk/pokkiri_box.webp',
  _card_ramune_bottle:      'icons/_card_junk/ramune_bottle.webp',
  _card_red_whistle:        'icons/_card_junk/red_whistle.webp',
  _card_rubber_band:        'icons/_card_junk/rubber_band.webp',
  _card_scratch_off:        'icons/_card_junk/scratch_off.webp',
  _card_smiley_pebble:      'icons/_card_junk/smiley_pebble.webp',
  _card_soda_can_tab:       'icons/_card_junk/soda_can_tab.webp',
  _card_stamp:              'icons/_card_junk/stamp.webp',
  _card_train_ticket_stub:  'icons/_card_junk/train_ticket_stub.webp',
  _card_watch_battery:      'icons/_card_junk/watch_battery.webp',
  _card_wine_cork:          'icons/_card_junk/wine_cork.webp',
  // Card art — artifacts
  _card_gunpowder:          'icons/artifacts/gunpowder.webp',
  _card_cattail:            'icons/artifacts/cattail.png',
  _card_nectar:             'icons/artifacts/nectar.png',
  _card_moss:               'icons/artifacts/moss.png',
  _card_pinecone:           'icons/artifacts/pinecone.png',
};

// Background scenes shown behind card art in the item info modal
const BG_SCENES = {
  green:               `${W}/d/d0/Beetleboy_Green_Background.webp`,
  purple:              `${W}/7/73/Beetleboy_Purple_Background.webp`,
  ladybug:             `${W}/9/93/Beetleboy_Ladybug_Background.webp`,
  monarch:             `${W}/1/11/Beetleboy_Monarch_Background.webp`,
  pond:                `${W}/3/35/Beetleboy_Pond_Background.webp`,
  bombardier:          `${W}/3/3f/Beetleboy_Bombardier_Background.webp`,
  stag:                `${W}/d/d1/Beetleboy_Stag_Background.webp`,
  sabertooth_longhorn: `${W}/9/94/Beetleboy_Sabertooth_Longhorn_Background.webp`,
  golden:              `${W}/5/54/Beetleboy_Golden_Background.webp`,
  giraffe_weevil:      `${W}/7/72/Beetleboy_Giraffe_Weevil_Background.webp`,
  pillbug:             `${W}/0/0f/Beetleboy_Pillbug_Background.webp`,
  christmas:           `${W}/f/f9/Beetleboy_Christmas_Background.webp`,
  skull:               `${W}/d/d0/Beetleboy_Skull_Background.webp`,
  sunset_moth:         `${W}/d/d3/Beetleboy_Sunset_Moth_Background.webp`,
  black_lotus:         `${W}/f/f5/Beetleboy_Black_Lotus_Background.webp`,
  camellia:            `${W}/2/2f/Beetleboy_Camellia_Background.webp`,
  daisy:               `${W}/6/67/Beetleboy_Daisy_Background.webp`,
  gallic_rose:         `${W}/7/74/Beetleboy_Gallic_Rose_Background.webp`,
  gazania:             `${W}/3/3a/Beetleboy_Gazania_Background.webp`,
  marigold:            `${W}/3/39/Beetleboy_Marigold_Background.webp`,
  milk_thistle:        `${W}/a/a8/Beetleboy_Milk_Thistle_Background.webp`,
  morning_glory:       `${W}/6/69/Beetleboy_Morning_Glory_Background.webp`,
  pincushion:          `${W}/5/5d/Beetleboy_Pincushion_Background.webp`,
  royal_poinciana:     `${W}/8/83/Beetleboy_Royal_Poinciana_Background.webp`,
  sunflower:           `${W}/c/c2/Beetleboy_Sunflower_Background.webp`,
};

// ── ITEM NAMES ────────────────────────────────────────────────────────────────
const NAMES = {
  // Beetles
  green:'Green Beetle', purple:'Purple Beetle', ladybug:'Ladybug',
  monarch:'Monarch', pond:'Pond Beetle', giraffe_weevil:'Giraffe Weevil',
  widow:'Black Widow', golden:'Golden Scarab', cucumber:'Striped Cucumber Beetle',
  christmas:'Christmas Beetle', bumblebee:'Bumble Bee', radbro:'Radbro',
  skull:'Skull Bug', candycane_tiger_moth:'Candycane Tiger Moth',
  imperial_tortoise:'Imperial Tortoise Beetle', pillbug:'Pillbug',
  bombardier:'Bombardier Beetle', goliath:'Goliath Beetle',
  stag:'Stag Beetle', sabertooth_longhorn:'Sabertooth Longhorn Beetle',
  sunset_moth:'Sunset Moth', mars_rhino:'Mars Rhino Beetle',
  golden_tiger:'Golden-Spotted Tiger Beetle', pondhawk:'Eastern Pondhawk',
  blue_longicorn:'Blue Longicorn Beetle',
  // Flowers
  daisy:'Daisy', sunflower:'Sunflower', poppy:'Poppy',
  gallic_rose:'Gallic Rose', st_johns_wort:"Spotted St. John's Wort",
  milk_thistle:'Milk Thistle', larkspur:'Two-spike Larkspur', petunia:'Large White Petunia',
  snapdragon:'Common Snapdragon', marigold:'Marigold', magnolia:'Southern Magnolia',
  carnation:'Chinese Pink Carnation', royal_poinciana:'Royal Poinciana',
  morning_glory:'Morning Glory', camellia:'Camellia', fringed_iris:'Fringed Iris',
  pincushion:'Pincushion', gazania:'Gazania',
  black_lotus:'Black Lotus', hellebore:'Green Hellebore',
  purple_passionflower:'Purple Passionflower',
  // Pollen
  pollen_common:'Tin Pollen', pollen_uncommon:'Bronze Pollen',
  pollen_rare:'Mithril Pollen', pollen_epic:'Adamantine Pollen',
  // Junk
  _junk_:'Junk', junk_cube_t1:'Junk Cube', junk_cube_t2:'Junk Tesseract',
  headphones_90s:'90s Headphones', burger_wrapper:'Burger Wrapper',
  chewed_eraser:'Chewed Eraser', event_band:'Event Band', guitar_pick:'Guitar Pick',
  origami_crane:'Origami Crane', pill_bottle:'Empty Pill Bottle', grenade_pin:'Grenade Pin',
  // Hammers
  hammer_t1:'Tin Hammer', hammer_t2:'Bronze Hammer',
  hammer_t3:'Mithril Hammer', hammer_t4:'Adamantine Hammer', hammer_t5:'Diamond Hammer',
  // Special / unique
  cheese:'Cheese', specimen_pin:'Specimen Pin', beetleboy_key:'BeetleBoy Key',
  // Artifacts
  nectar:'Nectar', cattail:'Cattail', pinecone:'Pinecone', moss:'Moss', gunpowder:'Gunpowder',
  // Trinkets
  chinese_coin:'Chinese Coin', prism:'Prism', roman_dodeca:'Roman Dodecahedron',
  arrowhead:'Arrowhead', titanium_cube:'Titanium Cube',
  oriental_fan:'Oriental Fan', mokia:'Mokia',
  thumb_drive:'Thumb Drive', jade_cabbage:'Jade Cabbage',
  juex_card:'Juex Card', cult_medallion:'CULT Medallion',
  d20:'D20', deck_of_cards:'Deck of Cards', compass:'Compass', stradivarius:'Stradivarius',
  engraved_lighter:'Engraved Lighter', goya_miniature:'Goya Miniature Painting',
  police_badge:'Police Badge', milady_fumoku:'Milady Fumoku', remilianet_id:'Reminet ID',
  // Trophies
  trophy_juex_card:'Juex Card Trophy',
  trophy_prism:'Prism Trophy', trophy_roman_dodeca:'Roman Dodecahedron Trophy',
  trophy_arrowhead:'Arrowhead Trophy', trophy_titanium_cube:'Titanium Cube Trophy',
  trophy_oriental_fan:'Oriental Fan Trophy', trophy_mokia:'Mokia Trophy',
  trophy_thumb_drive:'Thumb Drive Trophy', trophy_jade_cabbage:'Jade Cabbage Trophy',
  trophy_cult_medallion:'CULT Medallion Trophy',
  trophy_stradivarius:'Stradivarius Trophy', trophy_compass:'Compass Trophy',
  trophy_engraved_lighter:'Engraved Lighter Trophy',
  trophy_goya_miniature:'Goya Miniature Trophy',
  trophy_police_badge:'Police Badge Trophy', trophy_milady_fumoku:'Milady Fumoku Trophy',
  trophy_remilianet_id:'Reminet ID Trophy',
  trophy_deck_of_cards:'Deck of Cards Trophy', trophy_d20:'D20 Trophy',
  trophy_chinese_coin:'Chinese Coin Trophy',
};

// ── RARITY ────────────────────────────────────────────────────────────────────
const RARITY = {
  // Junk
  junk_cube_t1:'jnk', junk_cube_t2:'jnk',
  // Tin
  green:'tin', daisy:'tin', sunflower:'tin', poppy:'tin',
  petunia:'tin', snapdragon:'tin', carnation:'tin',
  pollen_common:'tin', hammer_t1:'tin', beetleboy_key:'tin',
  // Bronze
  purple:'brz', ladybug:'brz', gallic_rose:'brz', st_johns_wort:'brz',
  milk_thistle:'brz', marigold:'brz', magnolia:'brz', pollen_uncommon:'brz',
  hammer_t2:'brz', cucumber:'brz',
  // Mithril
  monarch:'mth', pond:'mth', royal_poinciana:'mth', morning_glory:'mth',
  camellia:'mth', fringed_iris:'mth', pollen_rare:'mth', hammer_t3:'mth',
  giraffe_weevil:'mth', christmas:'mth', imperial_tortoise:'mth',
  pillbug:'mth', skull:'mth', nectar:'mth', cattail:'mth',
  bumblebee:'mth', golden_tiger:'mth', blue_longicorn:'mth',
  // Adamantine
  pincushion:'adm', gazania:'adm', hellebore:'adm', larkspur:'adm',
  purple_passionflower:'adm', pollen_epic:'adm', hammer_t4:'adm', pondhawk:'adm',
  bombardier:'adm', goliath:'adm', stag:'adm', sabertooth_longhorn:'adm',
  sunset_moth:'adm', gunpowder:'adm', moss:'adm', pinecone:'adm',
  // Diamond
  golden:'dia', widow:'dia', black_lotus:'dia', hammer_t5:'dia',
  mars_rhino:'dia', candycane_tiger_moth:'dia',
  // Special (trinkets + trophies)
  chinese_coin:'pnk', prism:'pnk', roman_dodeca:'pnk', arrowhead:'pnk',
  titanium_cube:'pnk', oriental_fan:'pnk', mokia:'pnk', thumb_drive:'pnk',
  jade_cabbage:'pnk', juex_card:'pnk', cult_medallion:'pnk',
  d20:'pnk', deck_of_cards:'pnk', compass:'pnk', stradivarius:'pnk',
  engraved_lighter:'pnk', goya_miniature:'pnk',
  police_badge:'pnk', milady_fumoku:'pnk', remilianet_id:'pnk',
  specimen_pin:'pnk',
  trophy_juex_card:'pnk', trophy_prism:'pnk', trophy_roman_dodeca:'pnk',
  trophy_arrowhead:'pnk', trophy_titanium_cube:'pnk', trophy_oriental_fan:'pnk',
  trophy_mokia:'pnk', trophy_thumb_drive:'pnk', trophy_jade_cabbage:'pnk',
  trophy_cult_medallion:'pnk', trophy_stradivarius:'pnk', trophy_deck_of_cards:'pnk',
  trophy_compass:'pnk', trophy_chinese_coin:'pnk', trophy_milady_fumoku:'pnk',
  trophy_goya_miniature:'pnk', trophy_police_badge:'pnk',
  trophy_engraved_lighter:'pnk', trophy_remilianet_id:'pnk', trophy_d20:'pnk',
};

// ── SCIENTIFIC NAMES ──────────────────────────────────────────────────────────
const SCIENTIFIC = {
  // Beetles
  green:                'Chrysolina graminis',
  ladybug:              'Coccinella septempunctata',
  purple:               'Chrysolina sturmi',
  christmas:            'Stephanorrhina guttata',
  giraffe_weevil:       'Trachelophorus giraffa',
  imperial_tortoise:    'Stolas imperialis',
  monarch:              'Danaus plexippus',
  pillbug:              'Armadillidium pulchellum',
  pond:                 'Hydrochara caraboides',
  skull:                'Eucorysses grandis',
  bumblebee:            'Bombus terrestris',
  golden_tiger:         'Cicindela aurulenta',
  bombardier:           'Brachinus explodens',
  goliath:              'Goliathus goliatus',
  sabertooth_longhorn:  'Macrodontia cervicornis',
  stag:                 'Dorcus hopei binodulosus',
  sunset_moth:          'Chrysiridia rhipheus',
  pondhawk:             'Erythemis simplicicollis',
  golden:               'Chrysina resplendens',
  mars_rhino:           'Megasoma mars',
  candycane_tiger_moth: 'Spilosoma congrua',
  cucumber:             'Acalymma vittatum',
  widow:                'Latrodectus mactans',
  // Flowers
  daisy:                'Leucanthemum vulgare',
  poppy:                'Papaver rhoeas',
  sunflower:            'Helianthus annuus',
  petunia:              'Petunia axillaris',
  snapdragon:           'Antirrhinum majus',
  gallic_rose:          'Rosa gallica',
  marigold:             'Calendula officinalis',
  magnolia:             'Magnolia grandiflora',
  milk_thistle:         'Silybum marianum',
  st_johns_wort:        'Hypericum punctatum',
  camellia:             'Camellia japonica',
  morning_glory:        'Ipomoea tricolor',
  royal_poinciana:      'Delonix regia',
  gazania:              'Gazania x splendens',
  pincushion:           'Leucospermum praecox',
  black_lotus:          'Nelumbo nucifera',
  larkspur:             'Delphinium distichum',
  carnation:            'Dianthus chinensis',
  hellebore:            'Helleborus viridis',
  fringed_iris:         'Iris japonica',
  purple_passionflower: 'Passiflora incarnata',
  // Pollen
  pollen_common:        'Pulvis stannus',
  pollen_uncommon:      'Pulvis bronzium',
  pollen_rare:          'Pulvis mithrilum',
  pollen_epic:          'Pulvis adamantinus',
  // Junk
  bike_reflector:       'Speculatus velocipedus',
  bottle_cap:           'Operculum metallicum',
  chip_bag:             'Sacculus crepitus',
  chocolate_bar:        'Barra dulcis',
  chocolate_wrapper:    'Tegmen chocolatus',
  cigarette_butt:       'Fumigatus relictus',
  coffee_can:           'Cylindrus caffeinatus',
  cracker_wrapper:      'Involucrum biscuitus',
  empty_noodle_cup:     'Ramenus vacuus',
  green_army_man:       'Militus plasticus',
  gum_wrapper:          'Involucrum masticatus',
  jack_adapter:         'Adaptorus audius',
  juicebox:             'Cartonus succulentus',
  junk_cube_t1:         'Cubus junketii',
  junk_cube_t2:         'Cubus junketii major',
  marble:               'Sphericus vitreus',
  paperclip:            'Ferrum clipsius',
  pebble:               'Petrus minimus',
  pokkiri_box:          'Biscuitus japonicus',
  ramune_bottle:        'Vitrum marmoratus',
  red_whistle:          'Fistula rubra',
  rubber_band:          'Elasticus circularis',
  scratch_off:          'Fortuna rasilis',
  smiley_pebble:        'Petrus felix',
  soda_can_tab:         'Tirulus aluminus',
  stamp:                'Sigillum postalis',
  train_ticket_stub:    'Transitum fragmentum',
  watch_battery:        'Energia horologii',
  wine_cork:            'Quercus tapperus',
};

// ── DESCRIPTIONS ─────────────────────────────────────────────────────────────
const DESCRIPTIONS = {
  // Beetles
  green:                'Tansy beetle',
  ladybug:              'Common ladybug',
  purple:               'Violet leaf beetle',
  christmas:            'Spotted flower beetle',
  giraffe_weevil:       'Giraffe weevil',
  imperial_tortoise:    'Imperial tortoise beetle',
  monarch:              'Monarch',
  pillbug:              'Beautiful pill woodlouse',
  pond:                 'Lesser silver water beetle',
  skull:                'Death head bug',
  bumblebee:            'Buff-tailed bumblebee',
  bombardier:           'Bombardier beetle',
  goliath:              'Goliath beetle',
  sabertooth_longhorn:  'Sabertooth longhorn beetle',
  stag:                 'Japanese great stag beetle',
  sunset_moth:          'Madagascan sunset moth',
  pondhawk:             'Eastern pondhawk',
  golden:               'Jewel scarab',
  mars_rhino:           'Mars rhino beetle',
  widow:                'Southern Black Widow',
  golden_tiger:         'Golden-spotted tiger beetle',
  cucumber:             'Striped cucumber beetle',
  candycane_tiger_moth: 'New Hope tiger moth',
  // Flowers
  daisy:                'Oxeye daisy',
  poppy:                'Common poppy',
  sunflower:            'Common sunflower',
  petunia:              'Large white petunia',
  snapdragon:           'Common snapdragon',
  gallic_rose:          'Gallic rose',
  marigold:             'Pot marigold',
  magnolia:             'Southern magnolia',
  milk_thistle:         'Milk thistle',
  st_johns_wort:        "Spotted St. John's wort",
  camellia:             'Japanese camellia',
  morning_glory:        'Garden morning glory',
  royal_poinciana:      'Royal poinciana',
  gazania:              'Garden gazania',
  pincushion:           'Mossel bay pincushion',
  black_lotus:          'Sacred lotus (black)',
  larkspur:             'Two-spike larkspur',
  carnation:            'Chinese pink carnation',
  hellebore:            'Green hellebore',
  fringed_iris:         'Fringed iris',
  purple_passionflower: 'Purple passionflower',
  // Pollen
  pollen_common:        'From Tin flowers',
  pollen_uncommon:      'From Bronze flowers',
  pollen_rare:          'From Mithril flowers',
  pollen_epic:          'From Adamantine flowers',
  // Hammers
  hammer_t1:            '+0% craft bonus, 10% break chance',
  hammer_t2:            '+5% craft bonus, 5% break chance',
  hammer_t3:            '+20% craft bonus, 10% break chance',
  hammer_t4:            '+35% craft bonus, 2% break chance',
  hammer_t5:            '+90% craft bonus, 1% break chance',
  // Junk
  bike_reflector:       'Safety red',
  bottle_cap:           'Not a currency yet',
  chip_bag:             'Mostly air',
  chocolate_bar:        'Slightly melted',
  chocolate_wrapper:    'Still good.',
  cigarette_butt:       'The cure.',
  coffee_can:           'SUPER busy.',
  cracker_wrapper:      'Oh crumbs',
  empty_noodle_cup:     'Delicious styrofoam',
  green_army_man:       'OOORAAHH',
  gum_wrapper:          'Tattoos not included',
  jack_adapter:         'A relic of the early 21st century',
  juicebox:             'Beetlejuice signature flavor',
  junk_cube_t1:         'Encapsulated detritus',
  junk_cube_t2:         'Greater than the sum of its parts',
  marble:               'Faded swirl',
  paperclip:            'Standard silver',
  pebble:               'An interesting shade of blue…',
  pokkiri_box:          'Crispy biscuit sticks',
  ramune_bottle:        'Comes with free marble',
  red_whistle:          'Universal frequency',
  rubber_band:          'Bully grade',
  scratch_off:          'Non-winning',
  smiley_pebble:        'hi',
  soda_can_tab:         'A whit of chainmail',
  stamp:                'Do not lick',
  train_ticket_stub:    'I love my station',
  watch_battery:        'Extra spicy flavor',
  wine_cork:            'Celebrated for its excellence',
};

// ── CATEGORIES ────────────────────────────────────────────────────────────────
// Drives inventory display order and category grouping.
const CATEGORIES = [
  ['Beetles',   ['green','purple','ladybug','cucumber','monarch','pond','giraffe_weevil',
                 'pillbug','imperial_tortoise','christmas','skull',
                 'bumblebee','golden_tiger','blue_longicorn',
                 'goliath','bombardier','pondhawk','stag','sabertooth_longhorn','sunset_moth',
                 'golden','widow','candycane_tiger_moth','mars_rhino',
                 'radbro']],
  ['Flowers',   ['daisy','sunflower','poppy','petunia','snapdragon','carnation',
                 'gallic_rose','st_johns_wort','milk_thistle','marigold','magnolia',
                 'royal_poinciana','morning_glory','camellia','fringed_iris',
                 'pincushion','gazania','hellebore','larkspur','purple_passionflower',
                 'black_lotus']],
  ['Pollen',    ['pollen_common','pollen_uncommon','pollen_rare','pollen_epic']],
  ['Junk',      ['junk_cube_t1','junk_cube_t2']],
  ['Artifacts', ['nectar','cattail','pinecone','moss','gunpowder']],
  ['Trinkets',  ['chinese_coin','prism','roman_dodeca','arrowhead',
                 'titanium_cube','oriental_fan','mokia','thumb_drive','jade_cabbage',
                 'juex_card','cult_medallion','d20',
                 'deck_of_cards','compass','stradivarius',
                 'engraved_lighter','goya_miniature',
                 'police_badge','milady_fumoku','remilianet_id']],
  ['Hammers',   ['hammer_t1','hammer_t2','hammer_t3','hammer_t4','hammer_t5']],
  ['Special',   ['specimen_pin','beetleboy_key','christmas_item']],
];

// Derived lookups from CATEGORIES
const BEETLES = CATEGORIES.find(([n]) => n === 'Beetles')[1];
const HAMMERS = CATEGORIES.find(([n]) => n === 'Hammers')[1];
const KNOWN_KEYS = new Set(CATEGORIES.flatMap(([, keys]) => keys));

// Items that match this predicate are hidden from inventory (e.g. shelf items)
const HIDDEN = { has: (id) => id.endsWith('_shelf') };

// ── TROPHIES ──────────────────────────────────────────────────────────────────
// [key, displayName, hasImage]
const TROPHIES = [
  ['trophy_chinese_coin',     'Chinese Coin Trophy',        true],
  ['trophy_prism',            'Prism Trophy',               true],
  ['trophy_roman_dodeca',     'Roman Dodecahedron Trophy',  true],
  ['trophy_arrowhead',        'Arrowhead Trophy',           true],
  ['trophy_titanium_cube',    'Titanium Cube Trophy',       true],
  ['trophy_oriental_fan',     'Oriental Fan Trophy',        true],
  ['trophy_jade_cabbage',     'Jade Cabbage Trophy',        true],
  ['trophy_thumb_drive',      'Thumb Drive Trophy',         true],
  ['trophy_mokia',            'Mokia Trophy',               true],
  ['trophy_compass',          'Compass Trophy',             true],
  ['trophy_juex_card',        'Juex Card Trophy',           true],
  ['trophy_cult_medallion',   'CULT Medallion Trophy',      true],
  ['trophy_stradivarius',     'Stradivarius Trophy',        true],
  ['trophy_police_badge',     'Police Badge Trophy',        true],
  ['trophy_goya_miniature',   'Goya Miniature Trophy',      true],
  ['trophy_milady_fumoku',    'Milady Fumoku Trophy',       true],
  ['trophy_remilianet_id',    'Reminet ID Trophy',          true],
  ['trophy_deck_of_cards',    'Deck of Cards Trophy',       true],
  ['trophy_d20',              'D20 Trophy',                 true],
  ['trophy_engraved_lighter', 'Engraved Lighter Trophy',   false],
];

// Populate KNOWN_KEYS with trophy keys (needs TROPHIES defined first)
TROPHIES.forEach(([k]) => KNOWN_KEYS.add(k));

// ── FLOWER GROUPS ─────────────────────────────────────────────────────────────
const TIN_FLOWERS     = ['daisy','sunflower','poppy','petunia','snapdragon','carnation'];
const BRONZE_FLOWERS  = ['gallic_rose','st_johns_wort','milk_thistle','marigold','magnolia'];
const MITHRIL_FLOWERS = ['royal_poinciana','morning_glory','camellia','fringed_iris'];
const ADAM_FLOWERS    = ['pincushion','gazania','hellebore','larkspur','purple_passionflower'];
const ALL_FLOWERS     = [...TIN_FLOWERS, ...BRONZE_FLOWERS, ...MITHRIL_FLOWERS, ...ADAM_FLOWERS, 'black_lotus'];

const FLOWER_TIERS = [
  [TIN_FLOWERS,    'Tin Flower'],
  [BRONZE_FLOWERS, 'Bronze Flower'],
  [MITHRIL_FLOWERS,'Mithril Flower'],
  [ADAM_FLOWERS,   'Adamantine Flower'],
];

function ingGroupLabel(group) {
  if (group === 'junk') return 'Any Junk';
  const tier = FLOWER_TIERS.find(([g]) => g === group);
  return tier ? tier[1] : iname(group[0]); // iname defined in app.js
}

// ── HAMMER STATS ──────────────────────────────────────────────────────────────
const HAMMER_STATS = {
  hammer_t1: { bonus: 0,  breakPer: 10 },
  hammer_t2: { bonus: 5,  breakPer: 5  },
  hammer_t3: { bonus: 20, breakPer: 10 },
  hammer_t4: { bonus: 35, breakPer: 2  },
  hammer_t5: { bonus: 90, breakPer: 1  },
};

// ── TROPHY REPEAT ─────────────────────────────────────────────────────────────
// When a trophy is crafted a second time, the player gets this item instead.
const TROPHY_REPEAT = {
  trophy_chinese_coin:      'chinese_coin',
  trophy_prism:             'prism',
  trophy_roman_dodeca:      'roman_dodeca',
  trophy_arrowhead:         'arrowhead',
  trophy_titanium_cube:     'titanium_cube',
  trophy_oriental_fan:      'oriental_fan',
  trophy_jade_cabbage:      'jade_cabbage',
  trophy_mokia:             'mokia',
  trophy_thumb_drive:       'thumb_drive',
  trophy_cult_medallion:    'cult_medallion',
  trophy_juex_card:         'juex_card',
  trophy_deck_of_cards:     'deck_of_cards',
  trophy_d20:               'd20',
  trophy_compass:           'compass',
  trophy_stradivarius:      'stradivarius',
  trophy_engraved_lighter:  'engraved_lighter',
  trophy_goya_miniature:    'goya_miniature',
  trophy_police_badge:      'police_badge',
  trophy_milady_fumoku:     'milady_fumoku',
  trophy_remilianet_id:     'remilianet_id',
};

// ── ASSEMBLE RECIPES ──────────────────────────────────────────────────────────
const AR = [
  { out:'junk_cube_t1', name:'Junk Cube',               ing:[{group:'junk',qty:2}] },
  { out:'junk_cube_t2', name:'Junk Tesseract',          ing:[{key:'junk_cube_t1',qty:3}] },
  { out:'specimen_pin', name:'Gamble for Specimen Pin', ing:[{key:'junk_cube_t2',qty:2}] },

  { out:'hammer_t1', name:'Tin Hammer',        unique:true, ing:[{key:'junk_cube_t1',qty:2}] },
  { out:'hammer_t2', name:'Bronze Hammer',     unique:true, ing:[{key:'hammer_t1',qty:1},{key:'junk_cube_t2',qty:1},{key:'pollen_common',qty:1}] },
  { out:'hammer_t3', name:'Mithril Hammer',    unique:true, ing:[{key:'hammer_t2',qty:1},{key:'junk_cube_t2',qty:1},{key:'pollen_uncommon',qty:1}] },
  { out:'hammer_t4', name:'Adamantine Hammer', unique:true, ing:[{key:'hammer_t3',qty:1},{key:'junk_cube_t2',qty:1},{key:'pollen_epic',qty:1}] },
  { out:'hammer_t5', name:'Diamond Hammer',    unique:true, ing:[{key:'hammer_t4',qty:1},{key:'junk_cube_t2',qty:1},{key:'pollen_epic',qty:1}] },

  { out:'pollen_common',   name:'Tin Pollen',        ing:[{group:TIN_FLOWERS,qty:2}] },
  { out:'pollen_uncommon', name:'Bronze Pollen',      ing:[{group:BRONZE_FLOWERS,qty:2}] },
  { out:'pollen_rare',     name:'Mithril Pollen',     ing:[{group:MITHRIL_FLOWERS,qty:2}] },
  { out:'pollen_epic',     name:'Adamantine Pollen',  ing:[{group:ADAM_FLOWERS,qty:2}] },

  { out:'beetleboy_key', name:'BeetleBoy Key', unique:true, ing:[{group:BRONZE_FLOWERS,qty:1},{key:'junk_cube_t1',qty:1}] },

  // ── Trophies — Tier 1: base artifact trophies ─────────────────────────────
  { out:'trophy_chinese_coin',  name:'Chinese Coin Trophy',       unique:true, ing:[{key:'junk_cube_t1',qty:2},{key:'pollen_common',qty:1}] },
  { out:'trophy_prism',         name:'Prism Trophy',              unique:true, ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_common',qty:1}] },
  { out:'trophy_roman_dodeca',  name:'Roman Dodecahedron Trophy', unique:true, ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_uncommon',qty:1}] },
  { out:'trophy_arrowhead',     name:'Arrowhead Trophy',          unique:true, ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_rare',qty:1}] },
  { out:'trophy_titanium_cube', name:'Titanium Cube Trophy',      unique:true, ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_epic',qty:1}] },

  // ── Trophies — Tier 2: coin-derived composites ────────────────────────────
  { out:'trophy_oriental_fan', name:'Oriental Fan Trophy', unique:true, ing:[{key:'chinese_coin',qty:1},{key:'pollen_common',qty:1}] },
  { out:'trophy_jade_cabbage', name:'Jade Cabbage Trophy', unique:true, ing:[{key:'chinese_coin',qty:1},{key:'roman_dodeca',qty:1}] },
  { out:'trophy_thumb_drive',  name:'Thumb Drive Trophy',  unique:true, ing:[{key:'roman_dodeca',qty:1},{key:'prism',qty:1}] },
  { out:'trophy_mokia',        name:'Mokia Trophy',        unique:true, ing:[{key:'titanium_cube',qty:1},{key:'roman_dodeca',qty:1}] },
  { out:'trophy_compass',      name:'Compass Trophy',      unique:true, ing:[{key:'arrowhead',qty:1},{key:'roman_dodeca',qty:1}] },

  // ── Trophies — Tier 3: item-dependent ─────────────────────────────────────
  { out:'trophy_juex_card',     name:'Juex Card Trophy',     unique:true, ing:[{key:'prism',qty:1},{key:'titanium_cube',qty:1}] },
  { out:'trophy_cult_medallion',name:'CULT Medallion Trophy',unique:true, ing:[{key:'juex_card',qty:1},{key:'chinese_coin',qty:1}] },

  // ── Trophies — Tier 4: composite chains ───────────────────────────────────
  { out:'trophy_stradivarius', name:'Stradivarius Trophy',  unique:true, ing:[{key:'jade_cabbage',qty:1},{key:'oriental_fan',qty:1}] },
  { out:'trophy_police_badge', name:'Police Badge Trophy',  unique:true, ing:[{key:'arrowhead',qty:1},{key:'titanium_cube',qty:1}] },
  { out:'trophy_goya_miniature',name:'Goya Miniature Trophy',unique:true,ing:[{key:'stradivarius',qty:1},{key:'arrowhead',qty:1}] },

  // ── Trophies — Tier 5: late-game ──────────────────────────────────────────
  { out:'trophy_milady_fumoku', name:'Milady Fumoku Trophy', unique:true, ing:[{key:'cult_medallion',qty:1},{key:'arrowhead',qty:1}] },
  { out:'trophy_remilianet_id', name:'Reminet ID Trophy',    unique:true, ing:[{key:'juex_card',qty:1},{key:'milady_fumoku',qty:1}] },

  // ── Trophy repeat crafts (gives item instead of trophy) ───────────────────
  { out:'chinese_coin',    reqTrophy:'trophy_chinese_coin',    ing:[{key:'junk_cube_t1',qty:2},{key:'pollen_common',qty:1}] },
  { out:'prism',           reqTrophy:'trophy_prism',           ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_common',qty:1}] },
  { out:'roman_dodeca',    reqTrophy:'trophy_roman_dodeca',    ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_uncommon',qty:1}] },
  { out:'arrowhead',       reqTrophy:'trophy_arrowhead',       ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_rare',qty:1}] },
  { out:'titanium_cube',   reqTrophy:'trophy_titanium_cube',   ing:[{key:'junk_cube_t2',qty:2},{key:'pollen_epic',qty:1}] },
  { out:'oriental_fan',    reqTrophy:'trophy_oriental_fan',    ing:[{key:'chinese_coin',qty:1},{key:'pollen_uncommon',qty:1}] },
  { out:'jade_cabbage',    reqTrophy:'trophy_jade_cabbage',    ing:[{key:'chinese_coin',qty:1},{key:'roman_dodeca',qty:1}] },
  { out:'thumb_drive',     reqTrophy:'trophy_thumb_drive',     ing:[{key:'roman_dodeca',qty:1},{key:'prism',qty:1}] },
  { out:'mokia',           reqTrophy:'trophy_mokia',           ing:[{key:'titanium_cube',qty:1},{key:'roman_dodeca',qty:1}] },
  { out:'compass',         reqTrophy:'trophy_compass',         ing:[{key:'arrowhead',qty:1},{key:'roman_dodeca',qty:1}] },
  { out:'juex_card',       reqTrophy:'trophy_juex_card',       ing:[{key:'prism',qty:1},{key:'titanium_cube',qty:1}] },
  { out:'cult_medallion',  reqTrophy:'trophy_cult_medallion',  ing:[{key:'juex_card',qty:1},{key:'chinese_coin',qty:1}] },
  { out:'stradivarius',    reqTrophy:'trophy_stradivarius',    ing:[{key:'jade_cabbage',qty:1},{key:'oriental_fan',qty:1}] },
  { out:'police_badge',    reqTrophy:'trophy_police_badge',    ing:[{key:'arrowhead',qty:1},{key:'titanium_cube',qty:1}] },
  { out:'goya_miniature',  reqTrophy:'trophy_goya_miniature',  ing:[{key:'stradivarius',qty:1},{key:'arrowhead',qty:1}] },
  { out:'milady_fumoku',   reqTrophy:'trophy_milady_fumoku',   ing:[{key:'cult_medallion',qty:1},{key:'arrowhead',qty:1}] },
  { out:'remilianet_id',   reqTrophy:'trophy_remilianet_id',   ing:[{key:'juex_card',qty:1},{key:'milady_fumoku',qty:1}] },
];

// Fast lookup: output key → recipe (first match wins)
const AR_BY_OUT = Object.fromEntries(AR.map(r => [r.out, r]));

// ── RECIPE TABLE ──────────────────────────────────────────────────────────────
// Displayed in the RCP tab. [ingredients, output, type, note]
const RECIPES = [
  // Smash — tier-up (risky)
  ['2× Tin Beetle',       'Bronze Beetle',              'smash', 'risky — use first smash of day only'],
  ['2× Bronze Beetle',    'Mithril Beetle',             'smash', 'risky — use first smash of day only'],
  ['2× Mithril Beetle',   'Adamantine Beetle',          'smash', 'risky — use first smash of day only'],
  ['2× Adamantine Beetle','Diamond Beetle',             'smash', 'risky — use first smash of day only'],
  ['2× Tin Flower',       'Bronze Flower',              'smash', 'risky — use first smash of day only'],
  ['2× Bronze Flower',    'Mithril Flower',             'smash', 'risky — use first smash of day only'],
  ['2× Mithril Flower',   'Adamantine Flower',          'smash', 'risky — use first smash of day only'],
  ['2× Adamantine Flower','Diamond Flower',             'smash', 'risky — use first smash of day only'],
  // Smash — beetle → flower transmutation
  ['Tin Beetle + Junk Cube',       'Tin Flower (random)',         'smash', 'one-way only'],
  ['Bronze Beetle + Junk Cube',    'Bronze Flower (random)',      'smash', 'one-way only'],
  ['Mithril Beetle + Junk Cube',   'Mithril Flower (random)',     'smash', 'one-way only'],
  ['Adamantine Beetle + Junk Cube','Adamantine Flower (random)',  'smash', 'one-way only'],
  // Smash — artifact creation
  ['Bronze Beetle + Bronze Pollen',  'Nectar or Cattail',          'smash', 'random outcome'],
  ['Mithril Beetle + Mithril Pollen','Pinecone, Moss or Gunpowder','smash', 'random outcome'],
  // Smash — artifact use
  ['Nectar + Ladybug',                               'Monarch',                    'smash', ''],
  ['Cattail + Ladybug',                              'Pond Beetle',                'smash', ''],
  ['Pinecone + Pond Beetle',                         'Goliath Beetle',             'smash', ''],
  ['Moss + Pond Beetle',                             'Stag Beetle',                'smash', ''],
  ['Gunpowder + Pond Beetle',                        'Bombardier Beetle',          'smash', ''],
  ['Gunpowder + Moss + Pinecone',                    'Black Lotus',                'smash', ''],
  // Smash — flower beetlecraft
  ['Fringed Iris + Monarch/Pond (sac Purple)',        'Blue Longicorn Beetle',      'smash', ''],
  ['Royal Poinciana + Mithril Beetle',               'Giraffe Weevil',             'smash', ''],
  ['Camellia + Mithril Beetle',                      'Pillbug',                    'smash', ''],
  ['Morning Glory + Mithril Beetle',                 'Imperial Tortoise Beetle',   'smash', ''],
  ['Pincushion + Adamantine Beetle',                 'Sabertooth Longhorn Beetle', 'smash', ''],
  ['Gazania + Adamantine Beetle',                    'Sunset Moth',                'smash', ''],
  ['Black Lotus + Sabertooth Longhorn + Sunset Moth','Mars Rhino Beetle',          'smash', ''],
  ['Monarch + Two-spike Larkspur + Purple (sac)',    'Golden-Spotted Tiger Beetle','smash', ''],
  // Smash — special
  ['Specimen Pin + Any Beetle + Green (sac)',         "That Beetle's Trophy",       'smash', 'any beetle species'],
];

// ── SMASH AUTOFILL MAP ────────────────────────────────────────────────────────
// Maps recipe label → slot fill spec for the SMASH UI autofill.
// {k:'key'} = specific item. {t:'beetle'|'flower', r:'tin'|'brz'|'mth'|'adm'} = best of type/rarity.
const SMASH_FILL_MAP = new Map([
  ['2× Tin Beetle',         {sm0:{t:'beetle',r:'tin'}, sm1:{t:'beetle',r:'tin'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Bronze Beetle',      {sm0:{t:'beetle',r:'brz'}, sm1:{t:'beetle',r:'brz'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Mithril Beetle',     {sm0:{t:'beetle',r:'mth'}, sm1:{t:'beetle',r:'mth'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Adamantine Beetle',  {sm0:{t:'beetle',r:'adm'}, sm1:{t:'beetle',r:'adm'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Tin Flower',         {sm0:{t:'flower',r:'tin'}, sm1:{t:'flower',r:'tin'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Bronze Flower',      {sm0:{t:'flower',r:'brz'}, sm1:{t:'flower',r:'brz'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Mithril Flower',     {sm0:{t:'flower',r:'mth'}, sm1:{t:'flower',r:'mth'}, sac:{t:'beetle',r:'tin'}}],
  ['2× Adamantine Flower',  {sm0:{t:'flower',r:'adm'}, sm1:{t:'flower',r:'adm'}, sac:{t:'beetle',r:'tin'}}],
  ['Tin Beetle + Junk Cube',        {sm0:{t:'beetle',r:'tin'}, sm1:{k:'junk_cube_t1'}, sac:{t:'beetle',r:'tin'}}],
  ['Bronze Beetle + Junk Cube',     {sm0:{t:'beetle',r:'brz'}, sm1:{k:'junk_cube_t1'}, sac:{t:'beetle',r:'tin'}}],
  ['Mithril Beetle + Junk Cube',    {sm0:{t:'beetle',r:'mth'}, sm1:{k:'junk_cube_t1'}, sac:{t:'beetle',r:'tin'}}],
  ['Adamantine Beetle + Junk Cube', {sm0:{t:'beetle',r:'adm'}, sm1:{k:'junk_cube_t1'}, sac:{t:'beetle',r:'tin'}}],
  ['Bronze Beetle + Bronze Pollen', {sm0:{t:'beetle',r:'brz'}, sm1:{k:'pollen_uncommon'}, sac:{t:'beetle',r:'tin'}}],
  ['Mithril Beetle + Mithril Pollen',{sm0:{t:'beetle',r:'mth'},sm1:{k:'pollen_rare'},     sac:{t:'beetle',r:'tin'}}],
  ['Nectar + Ladybug',       {sm0:{k:'nectar'},   sm1:{k:'ladybug'}, sac:{t:'beetle',r:'tin'}}],
  ['Cattail + Ladybug',      {sm0:{k:'cattail'},  sm1:{k:'ladybug'}, sac:{t:'beetle',r:'tin'}}],
  ['Pinecone + Pond Beetle', {sm0:{k:'pinecone'}, sm1:{k:'pond'},    sac:{t:'beetle',r:'tin'}}],
  ['Moss + Pond Beetle',     {sm0:{k:'moss'},     sm1:{k:'pond'},    sac:{t:'beetle',r:'tin'}}],
  ['Gunpowder + Pond Beetle',{sm0:{k:'gunpowder'},sm1:{k:'pond'},    sac:{t:'beetle',r:'tin'}}],
  ['Gunpowder + Moss + Pinecone',   {sm0:{k:'gunpowder'}, sm1:{k:'moss'}, sac:{k:'pinecone'}}],
  ['Fringed Iris + Monarch (sac Purple)', {sm0:{k:'fringed_iris'},sm1:{k:'monarch'},sac:{k:'purple'}}],
  ['Fringed Iris + Pond (sac Purple)',    {sm0:{k:'fringed_iris'},sm1:{k:'pond'},   sac:{k:'purple'}}],
  ['Royal Poinciana + Mithril Beetle',{sm0:{k:'royal_poinciana'},sm1:{t:'beetle',r:'mth'},sac:{t:'beetle',r:'tin'}}],
  ['Camellia + Mithril Beetle',       {sm0:{k:'camellia'},      sm1:{t:'beetle',r:'mth'},sac:{t:'beetle',r:'tin'}}],
  ['Morning Glory + Mithril Beetle',  {sm0:{k:'morning_glory'}, sm1:{t:'beetle',r:'mth'},sac:{t:'beetle',r:'tin'}}],
  ['Pincushion + Adamantine Beetle',  {sm0:{k:'pincushion'},    sm1:{t:'beetle',r:'adm'},sac:{t:'beetle',r:'tin'}}],
  ['Gazania + Adamantine Beetle',     {sm0:{k:'gazania'},       sm1:{t:'beetle',r:'adm'},sac:{t:'beetle',r:'tin'}}],
  ['Black Lotus + Sabertooth Longhorn + Sunset Moth',{sm0:{k:'black_lotus'},sm1:{k:'sabertooth_longhorn'},sac:{k:'sunset_moth'}}],
  ['Monarch + Two-spike Larkspur + Purple (sac)',    {sm0:{k:'monarch'},sm1:{k:'larkspur'},sac:{k:'purple'}}],
  ['Specimen Pin + Any Beetle + Green (sac)',         {sm0:{k:'specimen_pin'},sm1:{t:'beetle'},sac:{k:'green'}}],
]);
