"""Writes assets.js (which official backgrounds/cards are shipped) and makes
small versions for grids: icons/_bg/sm and icons/_card/sm (about 220px wide).
Run after adding images: python3 gen_assets.py"""
import glob, json, os
from PIL import Image
here = os.path.dirname(os.path.abspath(__file__))

def keys(d): return sorted(os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(here, d, "*.webp")))

def thumbs(d, width=220):
    out = os.path.join(here, d, "sm"); os.makedirs(out, exist_ok=True)
    made = 0
    for p in glob.glob(os.path.join(here, d, "*.webp")):
        dst = os.path.join(out, os.path.basename(p))
        if os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(p): continue
        im = Image.open(p); im.load()
        if im.width > width:
            im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
        im.save(dst, "WEBP", quality=72, method=6)
        made += 1
    return made

made = thumbs("icons/_bg") + thumbs("icons/_card")
out = ["// GENERATED by gen_assets.py - lists images shipped in icons/_bg and icons/_card (small versions in */sm)",
       "var LOCAL_BG = new Set(" + json.dumps(keys("icons/_bg")) + ");",
       "var LOCAL_CARD = new Set(" + json.dumps(keys("icons/_card")) + ");", ""]
open(os.path.join(here, "assets.js"), "w").write("\n".join(out))
print("assets.js:", len(keys("icons/_bg")), "backgrounds,", len(keys("icons/_card")), "cards;", made, "thumbnails made")
