"""Writes assets.js: which official backgrounds (icons/_bg) and character
cards (icons/_card) are available locally. Run after adding images:
python3 gen_assets.py"""
import glob, json, os
here = os.path.dirname(os.path.abspath(__file__))
def keys(d): return sorted(os.path.splitext(os.path.basename(p))[0] for p in glob.glob(os.path.join(here, d, "*.webp")))
out = ["// GENERATED by gen_assets.py - lists images shipped in icons/_bg and icons/_card",
       "const LOCAL_BG = new Set(" + json.dumps(keys("icons/_bg")) + ");",
       "const LOCAL_CARD = new Set(" + json.dumps(keys("icons/_card")) + ");", ""]
open(os.path.join(here, "assets.js"), "w").write("\n".join(out))
print("assets.js:", len(keys("icons/_bg")), "backgrounds,", len(keys("icons/_card")), "cards")
